name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
      
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Build and push Docker Image to Docker Hub
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: utamaro/demo
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
